id: PCAFBA14D
initial_creation_type: input
source_metadata:
  title: 'MSV 1,04: Varṣāvastu'
  language: sa
  volumes:
    25ea3cd6becc40d7a9b5002e379bfa21:
      title: Piṇḍoddāna
      base_file: Piṇḍoddāna.txt
      work_id: W871E0261
    82e5c8f5243f487b86f68c3565e5bc52:
      title: Uddāna 1
      base_file: Uddāna 1.txt
      work_id: WBEB0EE2F
    ce2ddaf10fce4e1d875b42538391f386:
      title: Uddāna 2
      base_file: Uddāna 2.txt
      work_id: WB7F7C835
    89df6f2d55334f3d99f3087f2b033d96:
      title: Uddāna 3
      base_file: Uddāna 3.txt
      work_id: W6B1A4464
  chapter_to_tile: {}
created_at: '2022-03-01T22:14:58.387818'
last_modified_at: '2022-03-01T22:14:58.387826'
